### ISSUE TITLE
Add v1 meta tag

### ISSUE THREAD

**Issue by milliams** [actions/upload-release-asset#23]
According to [the docs](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/about-actions#versioning-your-action), as well as following SemVer, actions should:

>Move the major version tag (v1, v2, etc.) to point to the Git ref of the current release

This is so that users can just do:

```yaml
uses: actions/upload-release-asset@v1
```

and always be on the latest, compatible release.

There is an action which claims to be able to do this automatically for you at https://github.com/marketplace/actions/actions-tagger

**Comment by eine** [comment]
Refs actions/create-release#16 and actions/toolkit#214

**Comment by eregon** [comment]
Indeed, it would be nice to add a `v1` tag to this action, per the official versioning documentation: https://github.com/actions/toolkit/blob/master/docs/action-versioning.md

Right now, everyone is hardcoding `@v1.0.1` which means it's going to be painful if something breaks as nobody would get the bug fix automatically.

**Comment by eregon** [comment]
@IAmHughes @bryanmacfarlane @mscoutermarsh (based on the replies from the referenced issues)
Could one of you add a `v1` tag to this action?

**Comment by bryanmacfarlane** [comment]
@IAmHughes is the main contributor here.  Happy to help with this and other issue if needed ...

**Comment by IAmHughes** [comment]
I just setup that action to automate it in #27. Thanks for your patience around this!
