### ISSUE TITLE
Mark this repository as unmaintained

### ISSUE THREAD

**Issue by andymckay** [actions/upload-release-asset#78]
Sadly we haven't got the time to maintain this repository as an official GitHub Action. In the last year or two since we originally published this, a large number of really good community Actions have appeared on the Marketplace for doing this.

We'd like to mark this repository as unmaintained and make it clear to users what their expectations should be.

People are of course free to fork this repository and maintain those forks if they like.

To do this we'll:
* [x] Remove it from the Marketplace 
* [x] Remove from any official GitHub documentation.
* [ ] Change the README.md to clearly reflect its new state.
* [ ] Update the README.md to point to other community Actions.
* [ ] Archive this repository, putting it read-only mode. It will continue to work for all existing Action users, but won't receive any updates.

**Comment by greyltc** [comment]
> a large number of really good community Actions have appeared on the Marketplace for doing this.

@andymckay Could you suggest some?

**Comment by rugk** [comment]
Also sad to see this go. Is not this an official GitHub validated Action?

**Comment by eine** [comment]
@rugk, see #58.

**Comment by epignatelli** [comment]
> a large number of really good community Actions have appeared on the Marketplace for doing 

Thank you for posting this at the very beginning.

Would you mind hinting us towards some of the actions you are talking about on the marketplace?

**Comment by hannesa2** [comment]
@hross I guess you are the maintainer here. Please can you add some other maintainers. Maybe the last 5 guys who contribute already ?

Sadly this is the current/future state of most github repos: The maintainer looses interest and the project dies slowly.
There is no relay race culture to prevent from dead project

**Comment by eine** [comment]
@hannesa2:

- #58
- https://github.com/actions/upload-release-asset/pull/79#discussion_r578399148

**Comment by ash0x0** [comment]
@andymckay I think you should at least merge #77 ASAP because I personally wasted time trying to use this an I see other people have as well. The PR covers the necessary bases and I ended up using [softprops/action-gh-release](https://github.com/softprops/action-gh-release) as you suggest. It's probably much better to merge it even if you don't archive immediately because there needs to be some indication to people who end up here that they shouldn't use this.
